jobs:
  include:
    - stage: test
      language: go
      go: 1.9
      dist: trusty
      before_install:
        # Setup some env variables
        - GO_FILES=$(find . -iname '*.go' )  # All the .go files
        - PKGS=$(go list ./... )             # All the import paths

        # Setup dependency management tool
        - go get -u github.com/golang/dep/cmd/dep

        # Install linters
        - go get -u github.com/golang/lint/golint              # Linter
        - go get -u github.com/kisielk/errcheck                # errcheck checks that you checked errors.

      install:
        - dep ensure
      script:
        - go vet -v $PKGS                   # go vet is the official Go static analyzer
        - errcheck -verbose $PKGS           # Check for unchecked errors
        - golint -set_exit_status $PKGS     # One last linter

    - language: node_js
      node_js: "8"
      before_install:
        - cd ui
      script:
        - npm run lint
        - npm run build
